### ISSUE TITLE
dartdocgen not able to find SDK

### ISSUE THREAD

**Issue by financeCoding** [dart-lang/homebrew-dart#16]
```
–(adam)–(0|ttys004)–(Tue Dec 02|10:02:46)— — -
–(~/dart)–($ git clone https://github.com/achilleasa/dart_cassandra_cql.git
–(adam)–(0|ttys004)–(Tue Dec 02|10:02:50)— — -
–(~/dart)–($ cd dart_cassandra_cql/ && pub install
[....]
–(adam)–(0|ttys004)–(Tue Dec 02|10:07:54)— — -
–(~/dart/dart_cassandra_cql)–($ dartdocgen --compile --no-include-sdk --no-include-dependent-packages --out docs --package-root ./packages  .
Using default options for documenting a single package: --start-page=dart_cassandra_cql
Package Root: ./packages
Added to libraries: ./lib/dart_cassandra_cql.dart
Added to libraries: ./lib/driver/client.dart
Added to libraries: ./lib/driver/connection.dart
Added to libraries: ./lib/driver/exceptions.dart
Added to libraries: ./lib/driver/logging.dart
Added to libraries: ./lib/driver/protocol.dart
Added to libraries: ./lib/driver/query.dart
Added to libraries: ./lib/driver/stream.dart
Added to libraries: ./lib/driver/types.dart
Skipping part "./lib/driver/client/client.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/client/result_stream.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/connection/async_queue.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/connection/connection.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/connection/connection_pool.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/connection/pool_configuration.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/connection/simple_connection_pool.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/exception/authentication_exception.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/exception/cassandra_exception.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/exception/connection_failed_exception.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/exception/connection_lost_exception.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/exception/driver_exception_exception.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/exception/no_healthy_connections_exception.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/exception/stream_reservation_exception.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/logging/logger.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/authentication/authenticator.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/authentication/password_authenticator.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/frame/frame_decompressor.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/frame/frame_parser.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/frame/frame_reader.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/frame/frame_writer.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/internal/exception_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/requests/auth_response_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/requests/batch_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/requests/execute_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/requests/prepare_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/requests/query_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/requests/register_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/requests/startup_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/auth_challenge_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/auth_success_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/authenticate_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/error_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/event_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/prepared_result_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/ready_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/result_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/result_metadata.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/rows_result_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/schema_change_result_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/set_keyspace_result_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/protocol/messages/responses/void_result_message.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/query/batch_query.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/query/query.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/query/query_interface.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/stream/chunked_input_reader.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/stream/chunked_output_writer.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/stream/type_decoder.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/stream/type_encoder.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/codec_registry.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/custom_type.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/frame.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/frame_header.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/tuple.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/type_spec.dart". Part files should be in "lib/src".
Added to libraries: ./lib/driver/types/uuid.dart
Skipping part "./lib/driver/types/enums/batch_type.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/compression.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/consistency.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/data_type.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/enum.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/error_code.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/event_registration_type.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/event_type.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/header_flag.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/header_version.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/opcode.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/protocol_version.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/query_flag.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/result_type.dart". Part files should be in "lib/src".
Skipping part "./lib/driver/types/enums/row_result_flag.dart". Part files should be in "lib/src".
Unhandled exception:
FileSystemException: Cannot find SDK directory starting from , path = '/usr/local/Cellar/dart/1.8.0-dev.4.6/libexec/bin/snapshots'
#0      rootDirectory (file:///Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/pkg/docgen/lib/src/package_helpers.dart:32)
#1      getMirrorSystem (file:///Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/pkg/docgen/lib/src/generator.dart:121)
#2      generateDocumentation (file:///Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/pkg/docgen/lib/src/generator.dart:82)
#3      docgen (file:///Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/pkg/docgen/lib/docgen.dart:51)
#4      main (file:///Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/pkg/docgen/bin/docgen.dart:43)
#5      main (file:///Volumes/data/b/build/slave/dart-editor-mac-dev/build/dart/xcodebuild/DerivedSources/ReleaseX64/utils_wrapper.dart:12)
#6      _startIsolate (dart:isolate-patch/isolate_patch.dart:237)
#7      _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:192)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)
```

**Comment by adarshaj** [comment]
I am still having this problem with ubuntu 14.04 and dart/unstable package here are the details -
```bash
$ sudo apt-cache show dart/unstable
Package: dart
Version: 1.9.0-dev.10.12-1
Architecture: amd64
Maintainer: Soren Gjesse <sgjesse@google.com>
Installed-Size: 33383
Depends: libc6 (>= 2.9), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.4.0)
Section: misc
Priority: optional
Filename: pool/main/d/dart/dart_1.9.0-dev.10.12-1_amd64.deb
Size: 11380608
SHA1: b6687d900ad04dd1cbc9c88165e82c815c256506
MD5sum: f45220bed23d00892d8caefaf7c4d2f0
Description: Dart SDK
Description-md5: df4e0c58c64c8811c7c8a1e72453e2f9

$ dart --version
Dart VM version: 1.9.0-dev.10.12 (Fri Mar 20 10:57:47 2015) on "linux_x64"
$ pub version
Pub 1.9.0-dev.10.12
```
When I try to generate documentation - 
```bash
$ dartdocgen --compile .
Using default options for documenting a single package: --start-page=XXX
Unhandled exception:
FileSystemException: Cannot find SDK directory starting from , path = '/usr/lib/dart/bin/snapshots'
#0      rootDirectory (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/lib/src/package_helpers.dart:32)
#1      ensureMovedViewerCode (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/lib/src/viewer.dart:70)
#2      docgen (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/lib/docgen.dart:50)
#3      main (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/bin/docgen.dart:43)
#4      main (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/out/ReleaseX64/obj/gen/utils_wrapper.dart:12)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:253)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```
Even passing `--sdk` doesn't help - 
```bash
$ dartdocgen --sdk /usr/lib/dart/ --compile .
Using default options for documenting a single package: --start-page=XXX
Unhandled exception:
FileSystemException: Cannot find SDK directory starting from , path = '/usr/lib/dart/bin/snapshots'
#0      rootDirectory (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/lib/src/package_helpers.dart:32)
#1      ensureMovedViewerCode (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/lib/src/viewer.dart:70)
#2      docgen (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/lib/docgen.dart:50)
#3      main (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/pkg/docgen/bin/docgen.dart:43)
#4      main (file:///tmp/tmpHEKZVn/dart-1.9.0-dev.10.12/dart/out/ReleaseX64/obj/gen/utils_wrapper.dart:12)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:253)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)
```
Exact same error when I do `export DART_SDK=/usr/lib/dart/` . 

However, It did work once right after first upgrade when I moved from `dart/stable` to `dart/unstable` and I can't make it work again. 

Solution/Workarounds?

**Comment by adarshaj** [comment]
Weird, the problem was with incremental generation of docs, I was trying to generate the documentation without removing `dartdoc-viewer` folder, when i do `rm -rf dartdoc-viewer` and then `dartdocgen --compile .` started working!

Though, I feel this is a very annoying behavior and absurd error message!

**Comment by moomoohk** [comment]
Thanks @adarshaj, that workaround helped. Hopefully this'll get fixed soon.

**Comment by sethladd** [comment]
Try using the new dartdoc tool. We don't intend to update dartdocgen, as dartdoc is coming soon. Sorry for the troubles here.
