### ISSUE TITLE
 Calling <<-EOS.undent is deprecated

### ISSUE THREAD

**Issue by Jens0512** [dart-lang/homebrew-dart#48]
Was told "Please report this to the dart-lang/dart tap!" so here i am .

```
➜  ~ brew info dart
dart-lang/dart/dart: stable 1.24.3, devel 2.0.0-dev.19.0
The Dart SDK
https://www.dartlang.org/
Not installed
From: https://github.com/dart-lang/homebrew-dart/blob/master/dart.rb
==> Options
--with-content-shell
	Download and install content_shell -- headless Dartium for testing
--with-dartium
	Download and install Dartium -- Chromium with Dart
--devel
	Install development version 2.0.0-dev.19.0
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart/dart.rb:72:in `caveats'
Please report this to the dart-lang/dart tap!

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart/dart.rb:72:in `caveats'
Please report this to the dart-lang/dart tap!

==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec

--with-dartium:
  To use with IntelliJ, set the Dartium execute home to:
    /usr/local/opt/dart/Chromium.app
```

**Comment by Jens0512** [comment]
Understood that this has now been fixed.
